FROM centos:centos6
MAINTAINER Phi Huynh <phi.huynh@nashtechglobal.com>

# See possible debug levels in man page (loglevel): http://linux.die.net/man/5/slapd.conf
ENV DEBUG_LEVEL=256
EXPOSE 389 636
VOLUME [ "/data" ]

# Update to last version

RUN yum -y update && \
    yum -y install openldap-servers openldap-clients && \
    yum clean all

COPY . /root

CMD ["/root/run.sh"]